[project]
name = "vqe-nisq-project"
version = "0.1.0"
description = "Comparative study of VQE ansatze and error mitigation strategies on NISQ-era quantum hardware"
authors = [
    { name = "Tuna Tyurkoglu", email = "tuna.tyurkoglu@tum.de" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "h5py>=3.16.0",
    "mitiq>=1.1.0",
    "mthree>=3.0.0",
    "numpy>=2.2.6",
    "openfermion>=1.8.1",
    "pandas>=2.3.3",
    "pennylane>=0.45.1",
    "pennylane-lightning>=0.45.0",
    "pennylane-qiskit>=0.45.0",
    "polars>=1.44.2",
    "pyarrow>=25.0.1",
    "pyscf>=2.14.0",
    "qiskit>=2.3.0",
    "qiskit-aer>=0.17.2",
    "qiskit-algorithms>=0.4.0",
    "qiskit-ibm-runtime>=0.45.1",
    "qiskit-nature>=0.8.0",
    "scipy>=1.17.1",
]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
